export default {
  GET_DATA_LOADING: 'GET_DATA_LOADING',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_ERROR: 'GET_DATA_ERROR',
  SELECT_GENRE: 'SELECT_GENRE',
  SELECT_MOVIE: 'SELECT_MOVIE',
  SET_IS_NAV: 'SET_IS_NAV',
};
